server:
  port: 1000

spring:
  application:
    # 服务名
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他微服务
          enabled: true
      routes:
        - id: jianshu
          uri: https://www.jianshu.com
          predicates:
            - Path=/jianshu/p/c8ac84e820cc
            #- TimeBetween=下午09:00,下午10:00
          filters:
            - StripPrefix=1
            - PreLog=name1,value1
    nacos:
      discovery:
        # 配置中心地址
        server-addr: localhost:8848
        # 指定命名空间 必须用ID配置
        #namespace: 407cdd4a-0df2-4990-9d88-6279d6793286
        # 指定集群
        cluster-name: SH
        metadata:
          #当前实例的版本
          version: v1
          #调用的目标实例的版本
          target-version: v1
    sentinel:
      transport:
        #sentinel服务器地址
        dashboard: 'http://localhost:8080'
        #关闭控制台懒加载
      eager: true
      filter:
        # 监控全部地址
        url-patterns: '/**'




management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info
