server:
  port: 1001

spring:
  application:
    # 服务名
    name: demo-server
  cloud:
    nacos:
      discovery:
        # 配置中心地址
        server-addr: localhost:8848
        # 指定命名空间 必须用ID配置
        namespace: 407cdd4a-0df2-4990-9d88-6279d6793286
        # 指定集群
        cluster-name: SH
        metadata:
          version: v1

